development:
  adapter: postgresql
  encoding: unicode
  database: sinatra_todo
  pool: 2
  username: webrev
  password:

production:
  url: <%= ENV['DATABASE_URL'] %>
  adapter: postgresql
  database: mydb
  host: localhost
  pool: 5
  timeout: 5000